### ISSUE TITLE
Too terse of error message when two servers try to launch on same port

### ISSUE THREAD

**Issue by petersnm** [emsenn/stirling#66]
INFO:stirling.daemons.servers.mud:Attempting to bind MUDServer daemon...
WARNING:stirling.daemons.servers.mud:Tried to started MUDServer() when it was already online.
Traceback (most recent call last):
  File "./run_engine.py", line 21, in <module>
    from stirling.daemons.servers import MUD, HTTP
ImportError: cannot import name 'HTTP'

**Comment by emsenn** [comment]
this should be fixed in 0.2.0
